#!/usr/bin/env bash
#script displays numbers from 1 to 100
#displays FizzBuzz when number is a multiple of 3 and 5
#displays Fizz when number is a multiple of 3
#displays Buzz when number is a multiple of 5
#otherwise displays the number
COUNT=1
while((COUNT<=100));do
     if [ "$((COUNT%3))" -eq 0 ] && [ "$((COUNT%5))" -eq 0 ] ;then
              echo "FizzBuzz"
     elif [ "$((COUNT%3))" -eq 0 ] ;then
              echo "Fizz"
     elif [ "$((COUNT%5))" -eq 0 ];then
              echo "Buzz"
  else
              echo "$COUNT"
fi
((COUNT++))
done;
