#!/usr/bin/env bash
#script to display best school 10 times while using a loop with a Hi on 9th line
COUNT=9
while((COUNT>=0));do
    echo "Best School"
    if [ "$COUNT" -eq 1 ] ;then
    echo "Hi"
    fi
((COUNT--))
done;
