#!/usr/bin/env bash
#script that displays numbers from 1 to 20
#displays bad luck from china on 4th loop
#displays bad luck from japan on 9th loop
#displays bad luck from italy on 17th loop
COUNT=1
while((COUNT<=20));do
        echo "$COUNT"
     case $COUNT in
          4) echo "bad luck from china"
              ;;
          9) echo "bad luck from japan"
              ;;
         17) echo "bad luck from italy"
              ;;
        esac
((COUNT++))
done;
