#!/usr/bin/env bash
#script that displays numbers from 1 to 20
#displays bad luck from China on 4th loop
#displays bad luck from Japan on 9th loop
#displays bad luck from Italy on 17th loop
COUNT=1
while((COUNT<=20));do
        echo "$COUNT"
     case $COUNT in
                4) echo "bad luck from China"
                         ;;
                9) echo "bad luck from Japan"
                         ;;
               17) echo "bad luck from Italy"
                         ;;
        esac
((COUNT++))
done;
