#!/usr/bin/env bash
#script that displays time in detail
h=0
m=1
while [ $h -le 12 ]; do
        echo "Hour: ${h}"
  while [ $m -lt 60 ]; do
        echo $m
     let m+=1
  done
    let m=1
    let h+=1
done
