#!/usr/bin/env bash
#sscript that creates a file containing PID, displays messages depending on the signal
function remove () {
     rm /var/run/myscript.pid
     exit
 }
   trap "echo I hate the kill command;remove" SIGTERM
   trap "echo Y U no love me?!;remove" SIGINT
   
echo $$ >> /var/run/myscript.pid
while true; do
   echo To infinity and beyond;
done
