#!/usr/bin/env bash
#script

startup(){
   ./manage_my_process &
   echo "$!" > /var/run/my_process.pid
  }

stopremove(){
   pkill -f ./manage_my_process
   rm /var/run/my_process.pid
  }

OPTION="$1"
if [ $# -eq 1 ]
then
   case $OPTION in
   "start")
       startup
       echo "manage_my_process started"
  ;;
    "stop")
       stopremove
       echo "manage_my_process stopped"
  ;;
    "restart")
       stopremove
       startup
       echo "manage_my_process restarted"
  ;;
*)
      echo "Usage: manage_my_process {start|stop|restart}
  ;;
esac
