#!/usr/bin/env bash
#script that starts stops and restarts when comanded
function startup(){
      ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

function stopremove(){
	 pkill -f './manage_my_process' 
	 rm /var/run/my_process.pid 
}

function restartnow(){
	stopremove
	startup
	echo "manage_my_process restarted"
}
if [ $# -eq 1 ] 
then
	OPTIONN="$1"
	case $OPTIONN in
	"start")
		startup
	echo "manage_my_process started"
	;;
	"stop")
		#stopremove
	      	echo "manage_my_process stopped"
	;;
        "restart")
	restartnow
	;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
       esac
else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
