#!/usr/bin/env bash
#script that starts stops and restarts when comanded
function start(){
      bash ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
   }

function stop(){
      [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid 
}

function restart(){
      stop
      start
        echo "manage_my_process restarted"
}

if [ $# -eq 1 ] 
then
	OPTIONN="$1"
	case $OPTIONN in
	"start")
		start
	echo "manage_my_process started"
	;;
        "stop")
		#stop
		[ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
	      	echo "manage_my_process stopped"
	;;
        "restart")
  	     restart
	;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
       esac
else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
